version: '3.3'

services:
  web:
    image: node:latest
    working_dir: /react_tournament
    command: bash -c "yarn install && yarn start"
    environment:
      PORT: 3001
      YARN_CACHE_FOLDER: /yarn_cache
    ports:
      - '3001:3001'
      - '3002:3002'
    volumes:
      - .:/react_tournament
      - yarn-cache:/yarn_cache

volumes:
  yarn-cache:
